### PR TITLE
:rocket: feat(networking): adding UDP common protocols (#1)

### PR DESCRIPTION
**Pull request by khoramism**
I've just added a section for design patterns, I was wondering if we could move all the API stuff in `general-software-engineering-skills` into a more structred folder and then put gRPC, graphql and rest in there.

Same approach would work for Oauth and JWT (into a section about authN and authZ). 

with regards
- Khoramism

### CODE REVIEW

**Review by mostafaghadimi — CHANGES_REQUESTED** [review]
Hi @khoramism jan, I hope you are doing well.


Thanks for your invaluable contribution to Data Engineering Wiki repository.

I really impressed of how you followed the structure of every single wiki page, like: introduction and learning resources sections.

There are some notes to mention:
- Currently, we keep `data-engineering-wiki` in sync with `data-engineering-roadmap` repository. It means that if we have any topic in roadmap, we also have it on wiki. From my point of view, adding design patterns to software engineering skills would be a good idea. I want to ask for help from my colleagues to express their ideas.
- UDP, can be added to roadmap. 

Also there are some issues with the PR:

-  There isn't any space in directory or file names. Therefore, `design pattern` should be renamed to `design-pattern`.
- File or directory names are all in lower case. So, `Behavioral Design patterns` should be renamed to `behavioral-design-patterns`
- The weight in the markdown specifies the order of content. Please revisit its value!


Sincerely,
Mostafa

**Comment by khoramism** [comment]
Hi @mostafaghadimi , thanks for your input, I'll definitely fix them up, let me know what to do with the design pattern section.

**Comment by khoramism** [comment]
Hello @niyushabaghayi , Thanks for your comment, I didn't honestly know that these repos were in-sync, I'll open a pr there and try to add them. 
I'll try to pick concepts from the roadmap from now on. 
 thanks :D

**Review by niyushabaghayi — CHANGES_REQUESTED** [review]
For now, I think we can have the UDP in the wiki since we have it on the roadmap as well.
About the design patterns I think there's no need to have this much detailed topics about design patterns in the Data Engineering roadmap.
@khoramism

**Comment by khoramism** [comment]
Alright, I've removed the design pattern section.

Thanks.

@niyushabaghayi

**Review by mostafaghadimi — APPROVED** [review]
Well done @khoramism jan. Really happy to hearing from you.

**Pull request merged**
